<?php
/**
 * @file
 * cards_twitter_pull.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function cards_twitter_pull_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_tweet_items'.
  $field_bases['field_tweet_items'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_tweet_items',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'number_integer',
  );

  // Exported field_base: 'field_tweet_key'.
  $field_bases['field_tweet_key'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_tweet_key',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  return $field_bases;
}
